import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import {Header} from "@/widgets/header";

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["cyrillic"],
});

export const metadata: Metadata = {
    title: "Next Pizza",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="ru"
            className={`${nunito.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
        <Header/>
        <main className="min-h-screen bg-white">
            {children}
        </main>
        </body>
        </html>
    );
}
